version: '3.9'
services:
  app:
    build: .
    container_name: exemplo_plantao
    restart: unless-stopped
    command: bash -c 'npm run dev'
    volumes:
      - .:/usr/app
    ports: 
      - 3000:3000